Refactor: Consolidate tests and centralize type definitions
kkrt-labs/kakarot-rpc pull request #1393
Opened 2024-09-20 14:24 UTC by eugypalu

Resolves: #1392 

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing

# What is the new behavior?

1. Consolidating Tests: All test files are moved to a single folder for better organization and maintainability.
2. Refactoring Types: Type definitions are centralized in types.ts, simplifying type management and ensuring consistency.

# Does this introduce a breaking change?

- [ ] Yes
- [ ] No

2024-09-23 08:49 UTC, ClementWalter submitted a review, later dismissed

2024-09-23 08:49 UTC, greged93 requested changes
waiting for hive

2024-09-23 15:17 UTC, tcoratger submitted a review, later dismissed

2024-10-04 15:26 UTC, greged93 commented
@eugypalu if you can rebase this we can merge!

2024-10-21 14:00 UTC, greged93 approved these changes

2024-10-21 15:38 UTC, greged93 approved these changes

2024-10-21 16:26 UTC, merged