Indexer refactoring: Constants
kkrt-labs/kakarot-rpc pull request #1396
Opened 2024-09-20 15:39 UTC by eugypalu

Resolves: #1394 

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing

# What is the new behavior?

- Typed the constants in the file constants.ts
- Moved the constants config, DEFAULT_BLOCK_GAS_LIMIT and IGNORED_KEYS to constants.ts

# Does this introduce a breaking change?

- [ ] Yes
- [ ] No

2024-09-23 06:49 UTC, greged93 requested changes
It looks good but I want to wait the reactivation of hive before merging any unneeded changes.

2024-09-23 08:47 UTC, ClementWalter submitted a review, later dismissed

2024-09-23 15:16 UTC, tcoratger approved these changes

2024-09-27 11:10 UTC, greged93 commented
hey @eugypalu couple of conflicts here, can you fix them?

2024-10-29 18:35 UTC, greged93 approved these changes

2024-10-29 18:36 UTC, merged