feat: kakarot testnet
kkrt-labs/kakarot-rpc pull request #725
Opened 2024-01-23 19:01 UTC by greged93

Time spent on this PR:

Resolves: #NA

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing

# What is the new behavior?
Start replacing most of the code with with queries to a mongo db.

# Does this introduce a breaking change?

- [ ] Yes
- [ ] No

2024-01-23 19:09 UTC, d-roak commented
wen testnet token?

2024-01-23 19:23 UTC, greged93 commented
plz make a PR fixing typos first

2024-01-24 09:49 UTC, Eikix requested changes
> Reviewed 4 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725)* status: 4 of 16 files reviewed, 9 unresolved discussions (waiting on @ClementWalter and @greged93)

___
*[`src/main.rs` line 50 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Noun0vf8jdt1mFUr0Ul:-Noun0vf8jdt1mFUr0Um:ble0ark) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/main.rs#L50)):*
> ```XML
>             .await?;
>     let db = db_client.database_with_options(
>         "Kakarot-Testnet-0",
> ```

is this name "important"?
if so, it should maybe be an env variable?
___
*[`src/main.rs` line 51 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Noun8Lg83TIgem6ONCo:-Noun8Lg83TIgem6ONCp:bvrr00) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/main.rs#L51)):*
> ```XML
>     let db = db_client.database_with_options(
>         "Kakarot-Testnet-0",
>         DatabaseOptions::builder().read_concern(ReadConcern::majority()).write_concern(WriteConcern::MAJORITY).build(),
> ```

lol why is their ReadConcern's majority a function but their write concern's is a constant?
___
*[`src/db_client/error.rs` line 10 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NounUaGEYwJxzBuFwFk:-NounUaHCnwAFczS0Ifw:bliuvs9) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/db_client/error.rs#L10)):*
> ```XML
> pub enum DatabaseError {
>     /// MongoDB error.
>     #[error("MongoDB error: {0}")]
> ```

We can use a transparent error here afaik
___
*[`src/db_client/error.rs` line 13 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NounYbv1kTO_3xVw5AO:-NounYbv1kTO_3xVw5AP:b-j44bvq) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/db_client/error.rs#L13)):*
> ```XML
>     MongoDbError(#[from] mongodb::error::Error),
>     /// Value not found in the database.
>     #[error("Did not find value in the database.")]
> ```

Is this case "not found" already inside mongodb errors?
___
*[`src/db_client/types/transaction.rs` line 12 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Nourac31-j0LT0tagep:-Nourac31-j0LT0tageq:b-7totxq) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/db_client/types/transaction.rs#L12)):*
> ```XML
> #[serde(rename_all = "camelCase")]
> pub struct JsonRpcTransaction {
>     #[serde(deserialize_with = "crate::db_client::types::serde::deserialize_h256")]
> ```

is this how Reth does it?

pretty clean! I wonder what are the alternatives and what motivates this approach.


We have: DB strings -> custom deserializer -> custom type (very close to reth type) -> reth type

is it good to have an intermediate type? we could directly deserialize into the reth type, but maybe having this type gives us more freedom
___
*[`src/db_client/types/transaction.rs` line 51 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NoupeHCCS98h7QJRZ_P:-NoupeHCCS98h7QJRZ_Q:bg9sp1r) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/db_client/types/transaction.rs#L51)):*
> ```XML
>     fn from(tx: JsonRpcTransaction) -> Self {
>         let y_parity = if tx.v > U256::from(1u8) { tx.v - U256::from(35u8) } else { tx.v };
>         let y_parity = Parity(y_parity.bit(0));
> ```

why do we need this line? i've never seen it before
___
*[`src/db_client/types/transaction.rs` line 78 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NouqMSa5VImiIPBwWdo:-NouqMSa5VImiIPBwWdp:bd8d7u9) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/db_client/types/transaction.rs#L78)):*
> ```XML
> #[derive(Debug, Deserialize)]
> pub struct DbTransactionHash {
>     pub tx: Hash,
> ```

why do we need this?
___
*[`src/db_client/types/serde/mod.rs` line 12 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Nouq3nlDVU0pJupKGCY:-Nouq3nlDVU0pJupKGCZ:bn5w68z) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/db_client/types/serde/mod.rs#L12)):*
> ```XML
>             D: Deserializer<'de>,
>         {
>             let s = String::deserialize(deserializer)?;
> ```

we can check for "sanity" the way starknet-rs works with felt! macro for instance
https://github.com/xJonathanLEI/starknet-rs/blob/49719f49a18f9621fc37342959e84900b600083e/starknet-macros/src/lib.rs#L51
___
*[`src/eth_rpc/servers/eth_rpc.rs` line 101 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NouqVNaCzdlQxu1YW_k:-NouqVNaCzdlQxu1YW_l:b-lcuanx) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/eth_rpc/servers/eth_rpc.rs#L101)):*
> ```XML
> 
>         let transactions = if full {
>             BlockTransactions::Full(
> ```

this is pretty awesome! I like it but I still think we should not have "find_all" logic in the eth_rpc, 
we could have low level abstractions such as this find all, 
and a second level of abstraction for specific usecases that our app needs, akin to an internal REST api 

db_client.full_block(EnumNumberOrHash) (if someone has BlockTag "latest" -> we simply getBlockNumber and then query the correct full block by number, so DB does not have to know the concept of latest)
db_client.transaction_by_index_and_block_hash
db_client.transaction_by_hash

etc. 

wdyt

that way it's way simpler to put this in DbClient trait and mock it


<!-- Sent from Reviewable.io -->

2024-01-24 15:19 UTC, Eikix commented on src/storage/database.rs
> +pub struct EthDatabase {
Let's add rustdoc, we'll thank ourselves later

2024-01-25 09:17 UTC, greged93 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725)* status: 1 of 24 files reviewed, 10 unresolved discussions (waiting on @ClementWalter and @Eikix)

___
*[`src/main.rs` line 50 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Noun0vf8jdt1mFUr0Ul:-Nout8rx6t_WGTqzZWDb:b-r1627o) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/main.rs#L50)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

is this name "important"?
if so, it should maybe be an env variable?
</blockquote></details>

Just the name of the db I made for testing, I can indeed make it a env value.
___
*[`src/main.rs` line 51 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Noun8Lg83TIgem6ONCo:-NoutG2tD3yVlBc5U-wS:b-fcizqh) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/main.rs#L51)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

lol why is their ReadConcern's majority a function but their write concern's is a constant?
</blockquote></details>

No clue, very weird indeed haha
___
*[`src/eth_rpc/servers/eth_rpc.rs` line 101 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NouqVNaCzdlQxu1YW_k:-NouvQv25ANN3m90UJzn:bun6hs1) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/eth_rpc/servers/eth_rpc.rs#L101)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

this is pretty awesome! I like it but I still think we should not have "find_all" logic in the eth_rpc, 
we could have low level abstractions such as this find all, 
and a second level of abstraction for specific usecases that our app needs, akin to an internal REST api 

db_client.full_block(EnumNumberOrHash) (if someone has BlockTag "latest" -> we simply getBlockNumber and then query the correct full block by number, so DB does not have to know the concept of latest)
db_client.transaction_by_index_and_block_hash
db_client.transaction_by_hash

etc. 

wdyt

that way it's way simpler to put this in DbClient trait and mock it
</blockquote></details>

Updated the abstraction.
___
*[`src/storage/database.rs` line 20 at r2](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#gh-1465077790:-NoztuhUDQTVyiByOMxw:bb6un1j) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/9ed884956acebfd58a95cfd0946f17603b8e7d93/src/storage/database.rs#L20)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

Let's add rustdoc, we'll thank ourselves later
</blockquote></details>

Done
___
*[`src/db_client/types/transaction.rs` line 12 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Nourac31-j0LT0tagep:-Nozu2HQ7smxFqdEU4Ef:b-sdxcz5) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/db_client/types/transaction.rs#L12)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

is this how Reth does it?

pretty clean! I wonder what are the alternatives and what motivates this approach.


We have: DB strings -> custom deserializer -> custom type (very close to reth type) -> reth type

is it good to have an intermediate type? we could directly deserialize into the reth type, but maybe having this type gives us more freedom
</blockquote></details>

Updated, now uses a custom deserialize function in order to go from serialized string to string and then deserializes this string into the reth primitives.
___
*[`src/db_client/types/transaction.rs` line 51 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NoupeHCCS98h7QJRZ_P:-Noutsmb5xz4i7wmI7xh:bqu4psi) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/db_client/types/transaction.rs#L51)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

why do we need this line? i've never seen it before
</blockquote></details>

In case of EIP155ReplayProtection, I need to get the parity. Since the v parameter in this case is 2*CHAIN_ID + 35 + y_parity, -> subtract 35 and check the last bit in order to get the y parity.
___
*[`src/db_client/types/transaction.rs` line 78 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NouqMSa5VImiIPBwWdo:-NouuJhOEjkS-WPVFYTa:b-yapnl9) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/db_client/types/transaction.rs#L78)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

why do we need this?
</blockquote></details>

This is a type I made in order to only query the tx hashes.
___
*[`src/db_client/types/serde/mod.rs` line 12 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Nouq3nlDVU0pJupKGCY:-NouuQRwB-RJMkPteOkw:bpg2eap) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/db_client/types/serde/mod.rs#L12)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

we can check for "sanity" the way starknet-rs works with felt! macro for instance
https://github.com/xJonathanLEI/starknet-rs/blob/49719f49a18f9621fc37342959e84900b600083e/starknet-macros/src/lib.rs#L51
</blockquote></details>

nice! did not know you could use `starts_with`.
___
*[`src/db_client/error.rs` line 13 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NounYbv1kTO_3xVw5AO:-NoutOgV6HO5bWTLbQ5Q:b82653f) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/db_client/error.rs#L13)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

Is this case "not found" already inside mongodb errors?
</blockquote></details>

Not really, because the client just returns a None if it can't find the value.


<!-- Sent from Reviewable.io -->

2024-01-26 09:48 UTC, Eikix requested changes
I can see now see clearer into your approach. 
I can sense a tradeoff here between two approaches. 

Here, you're abstracting the logic of high-level RPC methods in the trait Ethereum Provider, and leaving the implementation details to the EthereumAccessLayer struct  which has somewhat low-level usage of the DB. 

It's close to but not equivalent to creating a DbClient that abstracts away DB calls entirely for the client.

> Reviewed 2 of 11 files at r3, 3 of 21 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-:-Np47bjY1KmMzy8trlw5:b-5ggfy1)* status: 3 of 27 files reviewed, 9 unresolved discussions (waiting on @ClementWalter and @greged93)

___
*[`src/main.rs` line 50 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Noun0vf8jdt1mFUr0Ul:-Np-lPYeDseAnwv9g2Ui:b-tvme4c) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/main.rs#L50)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

Just the name of the db I made for testing, I can indeed make it a env value.
</blockquote></details>

ok let's make it an env with a default value
___
*[`src/eth_provider/provider.rs` line 59 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np49S_MEmMsweGY7FnF:-Np49S_N9QQuSo6pgqtF:b-c1a50v) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L59)):*
> ```XML
> /// Uses an access to a database to certain data, while
> /// the rest is fetched from the Starknet Provider.
> pub struct EthereumAccessLayer<SP>
> ```

We should rename this
Let me think
___
*[`src/eth_provider/provider.rs` line 74 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np48NgU6Wgc3ado0y-A:-Np48NgU6Wgc3ado0y-B:b-r0tnzd) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L74)):*
> ```XML
>     async fn block_number(&self) -> EthProviderResult<U64> {
>         let filter = doc! {};
>         let sort = doc! { "header.number": -1 };
> ```

how expensive are sort filters in mongodb?
___
*[`src/eth_provider/provider.rs` line 77 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np485XI8VqDQMAdFULV:-Np485XI8VqDQMAdFULW:b-bn2v2e) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L77)):*
> ```XML
>         let header: Option<StoredHeader> = self.database.get_one("headers", filter, sort).await?;
>         let block_number = match header {
>             Some(header) => header.header.number.ok_or(EthProviderError::ValueNotFound)?.as_limbs()[0],
> ```

why do we need the as_limbs[0]? doesnt feel clean
___
*[`src/eth_provider/provider.rs` line 223 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np47UmrExTqSTQRhMmq:-Np47UmrExTqSTQRhMmr:b-jkwya8) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L223)):*
> ```XML
>                 self.block_number().await
>             }
>             BlockNumberOrTag::Pending => todo!("pending block number not implemented"),
> ```

why not self.block_number() + 1
___
*[`src/eth_provider/utils.rs` line 7 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np45nOR-wtvD0Kk-Bsa:-Np45nOR-wtvD0Kk-Bsb:b-j1n7lk) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/utils.rs#L7)):*
> ```XML
> /// Converts an iterator of `Into<D>` into a `Vec<D>`.
> pub(crate) fn iter_into<D, S: Into<D>>(iter: impl IntoIterator<Item = S>) -> Vec<D> {
>     iter.into_iter().map(Into::into).collect::<Vec<_>>()
> ```

this should probably be called into_vec
___
*[`src/eth_provider/utils.rs` line 11 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np45yso1v4fcCCqlHyl:-Np45yso1v4fcCCqlHym:bfld0oz) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/utils.rs#L11)):*
> ```XML
> 
> /// Converts a key and value into a MongoDB filter.
> pub(crate) fn into_filter<T>(key: &str, value: T, width: usize) -> Document
> ```

this should probably be called into_db_filter

to not collide with other filters such as log filter or bloom filter
___
*[`src/db_client/error.rs` line 10 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NounUaGEYwJxzBuFwFk:-Np4439o-t5HLJ6IQDKs:bb6ywmx) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/db_client/error.rs#L10)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

We can use a transparent error here afaik
</blockquote></details>

LGTM
___
*[`src/eth_provider/types/transaction.rs` line 7 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np46QMrAQ5sKCEAZyu4:-Np46QMrAQ5sKCEAZyu5:b-4ehp6s) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/types/transaction.rs#L7)):*
> ```XML
> /// A full transaction as stored in the database
> #[derive(Debug, Deserialize)]
> pub struct StoredTransactionFull {
> ```

There is no need for the Full suffix
___
*[`src/eth_provider/types/serde/mod.rs` line 11 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np46xkV-b5oV8-HK3D_:-Np46xkW7N1PZW_Z3qvq:b-p1wnuy) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/types/serde/mod.rs#L11)):*
> ```XML
>     T: Deserialize<'de>,
> {
>     // Deserialize the map into a `HashMap<String, Value>`. This intermediate
> ```

can you add an example in the doc comment so it's clearer


<!-- Sent from Reviewable.io -->

2024-01-26 10:38 UTC, greged93 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725)* status: 3 of 27 files reviewed, 9 unresolved discussions (waiting on @ClementWalter and @Eikix)

___
*[`src/eth_provider/provider.rs` line 77 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np485XI8VqDQMAdFULV:-Np4KM3S5wxc5IZZ_e4D:bj0gi08) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L77)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

why do we need the as_limbs[0]? doesnt feel clean
</blockquote></details>

by default the Header type from RPC has a U256 for the number, while it's a U64 for the definition of the rpc method. `as_limbs()` returns a [u64; 4], so indexing directly can never fail.
___
*[`src/eth_provider/provider.rs` line 223 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np47UmrExTqSTQRhMmq:-Np4KgCP1UxQyP3ryOLH:b-vrbrjq) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L223)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

why not self.block_number() + 1
</blockquote></details>

could yeah, but this would also fail on db + starknet_provider
___
*[`src/eth_provider/utils.rs` line 7 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np45nOR-wtvD0Kk-Bsa:-Np4L0HABjScoTM0nBuF:b-c37163) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/utils.rs#L7)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

this should probably be called into_vec
</blockquote></details>

Yeah but I also wanted to translate the `map(Into::into)` part :/
___
*[`src/eth_provider/utils.rs` line 11 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np45yso1v4fcCCqlHyl:-Np4KzzG8_qZm-tSPS-N:b-pqov82) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/utils.rs#L11)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

this should probably be called into_db_filter

to not collide with other filters such as log filter or bloom filter
</blockquote></details>

makes sense
___
*[`src/eth_provider/types/transaction.rs` line 7 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np46QMrAQ5sKCEAZyu4:-Np4L7eH8nA3kKJ3PXeR:b-ffreo5) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/types/transaction.rs#L7)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

There is no need for the Full suffix
</blockquote></details>

what do you mean?
___
*[`src/eth_provider/types/serde/mod.rs` line 11 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np46xkV-b5oV8-HK3D_:-Np4LGD77N4xICV-a8zy:bb7oryy) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/types/serde/mod.rs#L11)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

can you add an example in the doc comment so it's clearer
</blockquote></details>

sure


<!-- Sent from Reviewable.io -->

2024-01-26 11:02 UTC, Eikix requested changes
> Dismissed @Eikix from a discussion.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725)* status: 3 of 27 files reviewed, 8 unresolved discussions (waiting on @ClementWalter and @greged93)

___
*[`src/eth_provider/provider.rs` line 77 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np485XI8VqDQMAdFULV:-Np4NP3y4zkuAE_UtIZo:b3b6r6b) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L77)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

by default the Header type from RPC has a U256 for the number, while it's a U64 for the definition of the rpc method. `as_limbs()` returns a [u64; 4], so indexing directly can never fail.
</blockquote></details>

shouldn't we catch an error if number > U64::max?
we could do
u64::from_be_bytes(header.header.number.ok_or(EthProviderError::ValueNotFound)?.to_be_bytes())?
___
*[`src/eth_provider/provider.rs` line 223 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np47UmrExTqSTQRhMmq:-Np4PcGr7LOSpMY-cmSG:b-tx01w2) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L223)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

could yeah, but this would also fail on db + starknet_provider
</blockquote></details>

what does that mean
___
*[`src/eth_provider/utils.rs` line 7 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np45nOR-wtvD0Kk-Bsa:-Np4Ql8n7igZWy3X2dZT:bbuygvh) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/utils.rs#L7)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

Yeah but I also wanted to translate the `map(Into::into)` part :/
</blockquote></details>

to be fair this is quite a clean chained map, I don't think it should be a util:) it should just be inlined


<!-- Sent from Reviewable.io -->

2024-01-26 11:03 UTC, Eikix requested changes
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725)* status: 3 of 27 files reviewed, 8 unresolved discussions (waiting on @ClementWalter and @greged93)

___
*[`src/eth_provider/types/transaction.rs` line 7 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np46QMrAQ5sKCEAZyu4:-Np4QxdNAwdb8lWvuBw1:b-9rhoma) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/types/transaction.rs#L7)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

what do you mean?
</blockquote></details>

why not call it StoredTransaction


<!-- Sent from Reviewable.io -->

2024-01-26 12:39 UTC, Eikix requested changes
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725)* status: 3 of 27 files reviewed, 8 unresolved discussions (waiting on @ClementWalter and @greged93)

___
*[`src/eth_provider/provider.rs` line 77 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np485XI8VqDQMAdFULV:-Np4m6_u8Ww4evlLtS-l:byai7mm) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L77)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

shouldn't we catch an error if number > U64::max?
we could do
u64::from_be_bytes(header.header.number.ok_or(EthProviderError::ValueNotFound)?.to_be_bytes())?
</blockquote></details>

i meant u64::from\_be\_bytes(header.header.number.ok\_or(EthProviderError::ValueNotFound)?.to\_be\_bytes())?.into()


<!-- Sent from Reviewable.io -->

2024-01-26 13:03 UTC, greged93 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725)* status: 3 of 27 files reviewed, 8 unresolved discussions (waiting on @ClementWalter and @Eikix)

___
*[`src/eth_provider/provider.rs` line 74 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np48NgU6Wgc3ado0y-A:-Np4mY7OBrfWYnDqQvPz:b-t2sd3g) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L74)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

how expensive are sort filters in mongodb?
</blockquote></details>

Based on this article it's ok if we have an index on it. 
https://www.mongodb.com/blog/post/performance-best-practices-indexing
I think on the first pass of the PR I will focus on migration, then we can do a second PR for performance on the mongo queries, what do you think?
___
*[`src/eth_provider/provider.rs` line 77 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np485XI8VqDQMAdFULV:-Np4qq--8JyZsO8epEUj:b-v8t9s1) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L77)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

i meant u64::from\_be\_bytes(header.header.number.ok\_or(EthProviderError::ValueNotFound)?.to\_be\_bytes())?.into()
</blockquote></details>

I see your point but the issue is that `from_be_bytes` doesn't return an error. I will have to return a custom error if header.header.number.ok\_or(EthProviderError::ValueNotFound)?.to\_be\_bytes().len() > 8
___
*[`src/eth_provider/provider.rs` line 223 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np47UmrExTqSTQRhMmq:-Np4nhsuAQNrZO1hg4fC:btdhbu0) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L223)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

what does that mean
</blockquote></details>

Means that we can do this, but both the database and the starknet provider will fail to return a value. I set it to todo! to not forget, but I think we should error out. We could directly return `ValueNotFound`.
___
*[`src/eth_provider/utils.rs` line 7 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np45nOR-wtvD0Kk-Bsa:-Np4owVn9HafWr9LsbG0:b2k9vrc) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/utils.rs#L7)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

to be fair this is quite a clean chained map, I don't think it should be a util:) it should just be inlined
</blockquote></details>

yeah but I had it twice in the code and will probably need it more, it's a very small utils :)
___
*[`src/eth_provider/types/transaction.rs` line 7 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np46QMrAQ5sKCEAZyu4:-Np4o5bbAuWaBKVIiI4I:b58c3bj) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/types/transaction.rs#L7)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

why not call it StoredTransaction
</blockquote></details>

Oh ok, because you can also have the `StoredTransactionHash` where you only query the transaction hash. 


<!-- Sent from Reviewable.io -->

2024-01-26 13:58 UTC, Eikix requested changes
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725)* status: 3 of 27 files reviewed, 6 unresolved discussions (waiting on @ClementWalter and @greged93)

___
*[`src/eth_provider/provider.rs` line 223 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np47UmrExTqSTQRhMmq:-Np52tG5DRJZgMjO5fDG:b-amfxti) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L223)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

Means that we can do this, but both the database and the starknet provider will fail to return a value. I set it to todo! to not forget, but I think we should error out. We could directly return `ValueNotFound`.
</blockquote></details>

i don't understand
___
*[`src/eth_provider/utils.rs` line 7 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np45nOR-wtvD0Kk-Bsa:-Np531DuCkJfI97BVUte:bb6un1j) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/utils.rs#L7)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

yeah but I had it twice in the code and will probably need it more, it's a very small utils :)
</blockquote></details>

Done
___
*[`src/eth_provider/types/transaction.rs` line 7 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np46QMrAQ5sKCEAZyu4:-Np5384FE7_6d0IRdC6z:b-4emdo) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/types/transaction.rs#L7)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

Oh ok, because you can also have the `StoredTransactionHash` where you only query the transaction hash.
</blockquote></details>

yeah but StoredTransaction we know that it's a tx, and txhash is a hash
___
*[`src/eth_provider/types/serde/mod.rs` line 11 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np46xkV-b5oV8-HK3D_:-Np53DCf4-zQjj4Qpj4Z:bb6un1j) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/types/serde/mod.rs#L11)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

sure
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-01-26 14:02 UTC, greged93 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725)* status: 3 of 27 files reviewed, 6 unresolved discussions (waiting on @ClementWalter and @Eikix)

___
*[`src/main.rs` line 50 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Noun0vf8jdt1mFUr0Ul:-Np53fFnCvFUtpYk0-au:b35wbcq) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/main.rs#L50)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

can we make it an env variable
</blockquote></details>

yes! finishing the provider but don't worry I still have this in mind haha
___
*[`src/eth_provider/provider.rs` line 77 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np485XI8VqDQMAdFULV:-Np53tcS4mWsDDfl3sxF:btmxa0i) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L77)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

ah fair point mhm alright! but I feel something isn't so "clean" here: we don't really know by looking at it if limbs[0] is the last 64 bits of the first 64 bits, depending on the layout (big endian, little endian, etc.)
</blockquote></details>

I made a change, basically will convert it to a slice and then check that slice.len() > 8 :)
___
*[`src/eth_provider/provider.rs` line 223 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np47UmrExTqSTQRhMmq:-Np543AJDa4sIKPS9QpY:b-d7bhn2) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L223)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

i don't understand
</blockquote></details>

will dm
___
*[`src/eth_provider/types/transaction.rs` line 7 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np46QMrAQ5sKCEAZyu4:-Np544kRBja2UsvDm5oJ:b-9rk1vd) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/types/transaction.rs#L7)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

yeah but StoredTransaction we know that it's a tx, and txhash is a hash
</blockquote></details>

ahhh so you would prefer `StoredTransaction` and `StoredHash`.


<!-- Sent from Reviewable.io -->

2024-01-29 07:42 UTC, Eikix requested changes
> Reviewed 1 of 21 files at r4, 1 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725)* status: 4 of 32 files reviewed, 13 unresolved discussions (waiting on @ClementWalter and @greged93)

___
*[`src/eth_provider/provider.rs` line 59 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np49S_MEmMsweGY7FnF:-NpJ4_Uf7ehRzT9tVGuE:b-w37flc) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L59)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

We should rename this
Let me think
</blockquote></details>

Let's rename EthDataProvider
___
*[`src/eth_provider/provider.rs` line 77 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np485XI8VqDQMAdFULV:-NpJ4jTo3ySmbnkyFWOX:bb7k0qh) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L77)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

I made a change, basically will convert it to a slice and then check that slice.len() > 8 :)
</blockquote></details>

lgtm
___
*[`src/eth_provider/provider.rs` line 223 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np47UmrExTqSTQRhMmq:-NpJ4sf05mrRPmBBzFKT:bb7k0qh) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L223)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

will dm
</blockquote></details>

lgtm
___
*[`src/eth_provider/provider.rs` line 347 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ5pFL2NXIc-BTin5Z:-NpJ5pFL2NXIc-BTin5_:b-x4j6mz) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/provider.rs#L347)):*
> ```XML
>         });
> 
>         dbg!(&database_filter);
> ```

do we want to leave dbg! macros around or is it a mistake
___
*[`src/eth_provider/database/types/receipt.rs` line 8 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ6vdSD_TDj8IePdHy:-NpJ6vdSD_TDj8IePdHz:bniykzq) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/database/types/receipt.rs#L8)):*
> ```XML
> pub struct StoredTransactionReceipt {
>     #[serde(deserialize_with = "crate::eth_provider::database::types::serde::deserialize_intermediate")]
>     pub receipt: TransactionReceipt,
> ```

should we make this field private? and in other new types? might be more idiomatic
___
*[`src/eth_provider/starknet/kakarot.rs` line 6 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ8w59EOQhVLHd-OJL:-NpJ8w59EOQhVLHd-OJM:b8kyxxe) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/starknet/kakarot.rs#L6)):*
> ```XML
> use starknet_abigen_parser;
> use starknet_crypto::FieldElement;
> ```

this file should probably not be called "kakarot", something to help understand we load environment variables such as constants or config, or contract_config
___
*[`src/eth_provider/starknet/kakarot.rs` line 11 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ8pxf6LSSdxi9pKNc:-NpJ8pxgBT7dws_J_FDu:b-zf1xw) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/starknet/kakarot.rs#L11)):*
> ```XML
>     let env_var = std::env::var(var_name).unwrap_or_else(|_| panic!("Missing environment variable {var_name}"));
> 
>     FieldElement::from_hex_be(&env_var).unwrap_or_else(|_| panic!("Invalid hex string for {var_name}"))
> ```

we should use expect here, no?
___
*[`src/eth_rpc/servers/eth_rpc.rs` line 20 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ9Pms2Sph9xz-alOJ:-NpJ9Pmt6-rT0jHLvwfp:b-2droqk) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_rpc/servers/eth_rpc.rs#L20)):*
> ```XML
> where
>     P: EthereumProvider,
>     SP: Provider + Send + Sync,
> ```

Let's add a todo to say we'll blast this dependency to SP
___
*[`src/eth_rpc/servers/eth_rpc.rs` line 23 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ9W32CnvZ9RQEJckQ:-NpJ9W32CnvZ9RQEJckR:bj4krvw) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_rpc/servers/eth_rpc.rs#L23)):*
> ```XML
> {
>     pub eth_provider: P,
>     pub kakarot_client: Arc<KakarotClient<SP>>,
> ```

are we also blasting kakarot client?
if so, should we add a todo?
___
*[`src/eth_provider/database/types/transaction.rs` line 21 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ77nD-4tB7ixCiMq1:-NpJ77nD-4tB7ixCiMq2:b-l11tsg) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/database/types/transaction.rs#L21)):*
> ```XML
> #[derive(Debug, Deserialize)]
> pub struct StoredTransactionHash {
>     pub tx: Hash,
> ```

I think this field should be called tx_hash and not tx
and the type should be H256, not Hash

not sure I understand why we have the intermediary struct Hash, especially since it wraps block hash but then is used for tx hash
___
*[`src/eth_provider/database/types/serde/mod.rs` line 11 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ7vch6BwC7fkC7E5G:-NpJ7vch6BwC7fkC7E5H:b6kljmw) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/database/types/serde/mod.rs#L11)):*
> ```XML
> /// e.g. U64(0x1234) is stored in the database as "0x1234" and thus arrives
> /// as a serialized string "\"0x1234\"").
> pub fn deserialize_intermediate<'de, D, T>(deserializer: D) -> Result<T, D::Error>
> ```

If I understand correctly, using this intermediate step allows to "sanitize" the string "\"0x1234\"" to become a Rust type String(0x1234), using serde crate?

this step is exactly equivalent to removing the backslash and " symbol ?



when reading the comment it's not clear what we achieve
___
*[`src/eth_provider/database/types/serde/mod.rs` line 20 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ8HZVBC0DBjO0hrTm:-NpJ8HZVBC0DBjO0hrTn:bw29nc5) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/database/types/serde/mod.rs#L20)):*
> ```XML
>     // H256) are stored as strings in the database. This caused problems when
>     // deserializing the transaction because the deserializer expects a serialized
>     // primitives, not a serialized string.
> ```

This comment is redundant, but also not so clear, it'd help a lot to show an example like
"\"0xSomeHash\"": "\"0x1234\"" -> {0xSomeHash: serde::Value(0x1234)} -> U64 ?

my example is probably bad, since i don't understand the steps involved
___
*[`src/eth_provider/types/transaction.rs` line 7 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np46QMrAQ5sKCEAZyu4:-NpJ70Vi3VSpYfqR-aXC:b5wjivq) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/types/transaction.rs#L7)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

ahhh so you would prefer `StoredTransaction` and `StoredHash`.
</blockquote></details>

StoredTransaction and StoredTransactionHash


<!-- Sent from Reviewable.io -->

2024-01-29 08:42 UTC, greged93 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725)* status: 4 of 36 files reviewed, 13 unresolved discussions (waiting on @ClementWalter and @Eikix)

___
*[`src/eth_provider/provider.rs` line 59 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np49S_MEmMsweGY7FnF:-NpJBTOCDNqQ6VIGKIup:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L59)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

Let's rename EthDataProvider
</blockquote></details>

Done.
___
*[`src/eth_provider/provider.rs` line 74 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np48NgU6Wgc3ado0y-A:-NpJBUO8-VqdA51EwDba:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/provider.rs#L74)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

ok fine with me
</blockquote></details>

Done.
___
*[`src/eth_provider/provider.rs` line 347 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ5pFL2NXIc-BTin5Z:-NpJBYerDLSNRX6Lp_RD:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/provider.rs#L347)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

do we want to leave dbg! macros around or is it a mistake
</blockquote></details>

Done.
___
*[`src/eth_provider/database/types/receipt.rs` line 8 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ6vdSD_TDj8IePdHy:-NpJBjoi68NqNNwAQE-K:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/database/types/receipt.rs#L8)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

should we make this field private? and in other new types? might be more idiomatic
</blockquote></details>

Done.
___
*[`src/eth_provider/starknet/kakarot.rs` line 6 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ8w59EOQhVLHd-OJL:-NpJF7Wv5EfymLN864fo:b-osj233) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/starknet/kakarot.rs#L6)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

this file should probably not be called "kakarot", something to help understand we load environment variables such as constants or config, or contract_config
</blockquote></details>

Why not Kakarot? The goal of this file is to encompass everything Kakarot related (class hash, addresses, contracts, helpers,...)
___
*[`src/eth_provider/starknet/kakarot.rs` line 11 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ8pxf6LSSdxi9pKNc:-NpJF1k9Bv8tHifZUPTX:bpuw004) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/starknet/kakarot.rs#L11)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

we should use expect here, no?
</blockquote></details>

I was using formatting to add the `var_name` and clippy gave me a warning.
___
*[`src/eth_rpc/servers/eth_rpc.rs` line 20 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ9Pms2Sph9xz-alOJ:-NpJGjDb1bivi6fqjLjt:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_rpc/servers/eth_rpc.rs#L20)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

Let's add a todo to say we'll blast this dependency to SP
</blockquote></details>

Done.
___
*[`src/eth_rpc/servers/eth_rpc.rs` line 23 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ9W32CnvZ9RQEJckQ:-NpJGjQL5UoitlFqZFDH:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_rpc/servers/eth_rpc.rs#L23)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

are we also blasting kakarot client?
if so, should we add a todo?
</blockquote></details>

Done.
___
*[`src/eth_provider/database/types/transaction.rs` line 21 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ77nD-4tB7ixCiMq1:-NpJBtdR2xU7aY55XM7Y:bpimzfj) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/database/types/transaction.rs#L21)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

I think this field should be called tx_hash and not tx
and the type should be H256, not Hash

not sure I understand why we have the intermediary struct Hash, especially since it wraps block hash but then is used for tx hash
</blockquote></details>

This is because the value that is returned from the db is a serialized structure in the form:
{
   tx: {
      hash: String
   }
}
So I need to have the correct structure to deserialize it into. I can rename the field tx to "tx_hash" with serde if you prefer.
___
*[`src/eth_provider/database/types/serde/mod.rs` line 11 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ7vch6BwC7fkC7E5G:-NpJCxKY0GDLHeGy-ffZ:b-ytez20) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/database/types/serde/mod.rs#L11)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

If I understand correctly, using this intermediate step allows to "sanitize" the string "\"0x1234\"" to become a Rust type String(0x1234), using serde crate?

this step is exactly equivalent to removing the backslash and " symbol ?



when reading the comment it's not clear what we achieve
</blockquote></details>

The database stores a string. So when the structure is serialized, what arrives from the db to the rpc is a serialized string. This step allows me to get a string, which can then be deserialized in to a `U64`, `U128`,...
You can't deserialize from a serialized string into a `U64` for example.
___
*[`src/eth_provider/database/types/serde/mod.rs` line 20 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ8HZVBC0DBjO0hrTm:-NpJEjYk2y7iVlopa-GL:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/database/types/serde/mod.rs#L20)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

This comment is redundant, but also not so clear, it'd help a lot to show an example like
"\"0xSomeHash\"": "\"0x1234\"" -> {0xSomeHash: serde::Value(0x1234)} -> U64 ?

my example is probably bad, since i don't understand the steps involved
</blockquote></details>

Done.
___
*[`src/eth_provider/types/transaction.rs` line 7 at r4](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Np46QMrAQ5sKCEAZyu4:-NpJBp8lCDd4xmFJumdh:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/2dc7950a0981503c7e2451f2efc1da2fff46afb6/src/eth_provider/types/transaction.rs#L7)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

StoredTransaction and StoredTransactionHash
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-29 11:07 UTC, Eikix requested changes
> Reviewed 1 of 32 files at r9, 8 of 28 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725)* status: 10 of 37 files reviewed, 5 unresolved discussions (waiting on @ClementWalter and @greged93)

___
*[`src/main.rs` line 50 at r1](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-Noun0vf8jdt1mFUr0Ul:-NpJSKCF8UcCkbQ8mdz6:bb7k0qh) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/14a57b335c7ed68786a6a76d3e8ffaf6d35eff24/src/main.rs#L50)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

yes! finishing the provider but don't worry I still have this in mind haha
</blockquote></details>

lgtm
___
*[`src/main.rs` line 53 at r10](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJSUfv7lgD8m2Q60f3:-NpJSUfv7lgD8m2Q60f4:baynxek) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/6f71ad58f0110f571d54c7ae16c4678e681ed5f3/src/main.rs#L53)):*
> ```XML
>     let db = Database::new(db_client.database_with_options(
>         &env_var("MONGO_DATABASE_NAME").expect("Missing MONGO_DATABASE_NAME from .env"),
>         DatabaseOptions::builder().read_concern(ReadConcern::majority()).write_concern(WriteConcern::MAJORITY).build(),
> ```

did we look into how to make this handle "read-only"?
___
*[`src/eth_provider/starknet/kakarot.rs` line 6 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ8w59EOQhVLHd-OJL:-NpJtVD55fucwHYHxPaZ:boobq7y) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/starknet/kakarot.rs#L6)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

Why not Kakarot? The goal of this file is to encompass everything Kakarot related (class hash, addresses, contracts, helpers,...)
</blockquote></details>

because kakarot is a name that may refer to many things:
kakarot core evm cairo programs
kakarot zkevm the rollup
etc.

if we want to keep it called kakarot, it should be called something more specific, kakarot_contracts for instance

and the rustdoc of the file should explain the intention behind this file
___
*[`src/eth_provider/database/types/transaction.rs` line 21 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ77nD-4tB7ixCiMq1:-NpJtHcIC1Y-wBbmVnjL:b-pr85tw) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/database/types/transaction.rs#L21)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

This is because the value that is returned from the db is a serialized structure in the form:
{
   tx: {
      hash: String
   }
}
So I need to have the correct structure to deserialize it into. I can rename the field tx to "tx_hash" with serde if you prefer.
</blockquote></details>

yes let's do that

and add a rustdoc comment with an example to explain why we have to do this, as it is seemingly unnatural
___
*[`src/eth_provider/database/types/serde/mod.rs` line 11 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ7vch6BwC7fkC7E5G:-NpJtQtZE_dk3eJqWhYQ:bb7k0qh) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/database/types/serde/mod.rs#L11)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

The database stores a string. So when the structure is serialized, what arrives from the db to the rpc is a serialized string. This step allows me to get a string, which can then be deserialized in to a `U64`, `U128`,...
You can't deserialize from a serialized string into a `U64` for example.
</blockquote></details>

lgtm


<!-- Sent from Reviewable.io -->

2024-01-29 11:22 UTC, greged93 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725)* status: 10 of 37 files reviewed, 5 unresolved discussions (waiting on @ClementWalter and @Eikix)

___
*[`src/main.rs` line 53 at r10](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJSUfv7lgD8m2Q60f3:-NpJw38i1dBswj5QhAZB:bmu819h) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/6f71ad58f0110f571d54c7ae16c4678e681ed5f3/src/main.rs#L53)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

did we look into how to make this handle "read-only"?
</blockquote></details>

Can't find a way to limit this to read-only
___
*[`src/eth_provider/starknet/kakarot.rs` line 6 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ8w59EOQhVLHd-OJL:-NpJvSrrD-WEzr_HHhOz:b9wh4g) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/starknet/kakarot.rs#L6)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

because kakarot is a name that may refer to many things:
kakarot core evm cairo programs
kakarot zkevm the rollup
etc.

if we want to keep it called kakarot, it should be called something more specific, kakarot_contracts for instance

and the rustdoc of the file should explain the intention behind this file
</blockquote></details>

imo it sits in the module eth_provider::starknet::kakarot so that should be clear to what we use it for no? In the context of the starknet access for the eth_provider, this is the Kakarot specific accesses.


<!-- Sent from Reviewable.io -->

2024-01-29 13:29 UTC, greged93 reviewed
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725)* status: 10 of 43 files reviewed, 5 unresolved discussions (waiting on @ClementWalter and @Eikix)

___
*[`src/eth_provider/database/types/transaction.rs` line 21 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ77nD-4tB7ixCiMq1:-NpKP2NX9SQeXb2wbzGM:b-896fix) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/database/types/transaction.rs#L21)):*
<details><summary><i>Previously, Eikix (Elias Tazartes) wrote…</i></summary><blockquote>

yes let's do that

and add a rustdoc comment with an example to explain why we have to do this, as it is seemingly unnatural
</blockquote></details>

Done.
___
*[`src/eth_provider/starknet/kakarot.rs` line 6 at r6](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-NpJ8w59EOQhVLHd-OJL:-NpKPIix1ePJCMBSLUrf:b53uxev) ([raw file](https://github.com/kkrt-labs/kakarot-rpc/blob/c741b951f99265c74a07ab7aabc5179055775e60/src/eth_provider/starknet/kakarot.rs#L6)):*
<details><summary><i>Previously, greged93 wrote…</i></summary><blockquote>

imo it sits in the module eth_provider::starknet::kakarot so that should be clear to what we use it for no? In the context of the starknet access for the eth_provider, this is the Kakarot specific accesses.
</blockquote></details>

changed to kakarot_core


<!-- Sent from Reviewable.io -->

2024-01-29 13:37 UTC, Eikix approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 28 files at r10, 2 of 12 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/kkrt-labs/kakarot-rpc/725#-:-NpKR0yfA-D2cnyoWA-4:bnfp4nl)* status: 13 of 43 files reviewed, all discussions resolved (waiting on @ClementWalter)



<!-- Sent from Reviewable.io -->

2024-01-29 13:45 UTC, merged